### ISSUE TITLE
inquiry about the paper classification

### ISSUE THREAD

**Issue by JustinDoIt** [Peldom/papers_for_protein_design_using_DL#1]
I have done similar things before, so I can submit PR if it will help.

But I wanna inquiry about the paper classification.

1. If classified according to the `model`, it can be divided into the `generative model` and `discriminant model`.
2. If classified according to the `architecture`, .... Convs-like, ResNet-like, ..., Transformer-like .....
3. classified according to the `tasks`, like [Kevin yang's repo](https://github.com/yangkky/Machine-learning-for-proteins)
4. classified according to the `input-output`, seems like this repo?

When I was doing similar work before, the classification problem confused me. It seems that there is no perfect scheme to weigh all parties?

**Comment by Peldom** [comment]
I thought the number of these papers wouldn't be quite much, and current classification scheme seems OK. 
These "model, architecture,..." can be **#Tags** if you prefer to tag these papers from different dimensions I suppose, but they might be a little bit tricky in markdown files. (TAGs-management-style is kind of trend in current OS)
